// Code generated by fffi generator; DO NOT EDIT.
case 0x00000bb8:
  {
    FFFI_FUNCTION_INVOCATION("ButtonV")
    auto label = receiveString();
    auto hiddenLabel = receiveString();
    auto icon = receiveString();
    auto variant = receiveValueSignMagnitude<int>();
    auto staticColor = receiveValueSignMagnitude<int>();
    auto style = receiveValueSignMagnitude<int>();
    auto size = receiveValueSignMagnitude<int>();
    auto justified = receiveValue<bool>();
    auto pending = receiveValue<bool>();
    auto disabled = receiveValue<bool>();
    uint16_t r;
    {
    auto r = DesignSystem::ButtonV(label, hiddenLabel, icon, variant, staticColor, style, size, justified, pending, disabled);
    sendEmptyString();
    sendValue<uint16_t>(r);
    flushSend();
  }
  }
  break;
