name: Build

on: 
  push:
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        default: false

jobs:
  build_ubuntu:
    name: build_ubuntu
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache-dependency-path: 'go.sum'
      - name: Install
        run: ./scripts/install.sh
      - name: Install distribution dependent
        run: ./scripts/install_ubuntu2204.sh
      # Enable tmate debugging of manually-triggered workflows if the input option was provided
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}
      - name: Generate fffi dispatching code
        run: ./common/generate.sh
      - name: Build ImGui Glfw Executable
        run: ./imgui_glfw/build.sh
      - name: Build Wasm
        run: ./imgui_wasm/build.sh
      - name: Build Skia Backend
        run: ./skia/build.sh
